### ISSUE TITLE
QLabsQCar.destroy() not able to destroy spawned vehicles

### ISSUE THREAD

**Issue by habibi1195** [quanser/Quanser_Interactive_Labs_Resources#2]
I'm trying to create a gymnasium environment to train RL models in the digital twin. However, it's becoming an issue where QLabs.QCar.destroy() is intermittently returning -1, making it impossible to reset the environment. 

I define a class QCarVehicle which takes as its argument the actor number. 
I instantiate two QCars and spawn them using a method defined in the QCarVehicle class which is essentially just the QLabsQCar.spawn method. After running their necessary actions, I need to reset the environment. 

When I run: QLabsQCar.destroy(), it occasionally returns -1. No other actions can be performed at this point.

**Comment by mrDataMeetsQ** [comment]
Thanks for reporting. We are looking into it. In the mean time, can you try the following two methods, 
1. Try placing a pause via a wait/sleep method of your choice between the destroy() method and QLabs function call right before it.
2. Try placing the destroy() method in a while loop that exits after a certain number of iterations or if a non-negative error code is received.

**Comment by habibi1195** [comment]
Hi, 

Is there anything to report on this issue? I'm still having the same issue. Here is a small test that tests one QCar to spawn and move a little before despawning, in a loop. Without failure, on the 4th loop, qlabs.destroy_all_spawned_actors() returns -1. (Apologies that Github code embed is sturggling to format everything properly)

`from qvl.qlabs import QuanserInteractiveLabs
from qvl.free_camera import QLabsFreeCamera
from qvl.basic_shape import QLabsBasicShape
from qvl.qcar import QLabsQCar
from qvl.environment_outdoors import QLabsEnvironmentOutdoors
import time
import math
import numpy as np
import matplotlib.pyplot as plt
import threading


class QCarSimulation(object):
    """
    Control the simulation of Quanser QCars in the digital twin
    """
    def __init__(self,
                 host='localhost',
                 init_params = None,
                 qlabs = QuanserInteractiveLabs()
                 ):
        self.init_params = init_params
        self.qlabs = qlabs
        self.vehicle = QLabsQCar(self.qlabs)
        self.lock = threading.Lock()
        
        print("Connecting to QLabs...")
        try:
            self.client = qlabs.open(host)
        except:
            print("Unable to connect to QLabs")
            return
        
        print("Connected")
        
    # def spawn_vehicle(self, actorNumber, location, rotation):
    #     self.vehicle.spawn_id(actorNumber=actorNumber, location=location, rotation=rotation)
        
    def despawn_all(self):
        return self.qlabs.destroy_all_spawned_actors()
        
    def spawn_camera(self,actorNumber, location, rotation):
        hCameraQCars = QLabsFreeCamera(self.qlabs)
        hCameraQCars.spawn_id(actorNumber=actorNumber, location=location, rotation=rotation)
        hCameraQCars.possess()
        
    
    def accelerate_forward(self, speed=0, turn=0, headlights=True, leftTurnSignal=False, 
                           rightTurnSignal=False, brakeSignal=False, reverseSignal=False):
        self.vehicle.set_velocity_and_request_state(forward=speed, turn=turn, headlights=True, leftTurnSignal=False, 
                               rightTurnSignal=False, brakeSignal=False, reverseSignal=False)
    
    def forward_times(self, speed=0, turn=0, headlights=True, leftTurnSignal=False, 
                           rightTurnSignal=False, brakeSignal=False, reverseSignal=False):
        x, location, rotation, frontHit, rearHit = self.vehicle.set_velocity_and_request_state(forward=speed, turn=turn, headlights=True, leftTurnSignal=False, 
                               rightTurnSignal=False, brakeSignal=False, reverseSignal=False)
        return x, location, rotation, frontHit, rearHit
    
    def close_connection(self):
        return self.qlabs.close()
    
class QCarVehicle(QCarSimulation):
    def __init__(self, actor_number):
        super().__init__()
        self.actor_number = actor_number
        self.squareSize = 100
        plt.ion()  # Turn on interactive mode for Matplotlib
        self.fig, self.ax = plt.subplots(figsize=(8, 8), dpi=100)
        self.ax.set_xlim(-self.squareSize, self.squareSize)
        self.ax.set_ylim(-self.squareSize, self.squareSize)
        self.ax.set_facecolor('black')  # Set background color to black
        self.lidarData, = self.ax.plot([], [], 'ro', markersize=1)
        
        
    def spawn_vehicle(self, location, rotation):
        return self.vehicle.spawn_id(self.actor_number, location, rotation)
    

    def set_speed(self, speed, duration):
        self.vehicle.set_velocity_and_request_state_degrees(forward=speed, turn = 0, headlights=True, leftTurnSignal=False, 
                               rightTurnSignal=False, brakeSignal=False, reverseSignal=False)
        
        time.sleep(duration)
        
        self.vehicle.set_velocity_and_request_state_degrees(forward=0, turn = 0, headlights=True, leftTurnSignal=False, 
                               rightTurnSignal=False, brakeSignal=False, reverseSignal=False)

    
    def set_turn(self, speed, turn, duration):
        self.vehicle.set_velocity_and_request_state_degrees(forward=speed, turn=turn, headlights=True, leftTurnSignal=False, 
                               rightTurnSignal=False, brakeSignal=False, reverseSignal=False)
        time.sleep(duration)
        self.vehicle.set_velocity_and_request_state_degrees(forward=0, turn=turn, headlights=True, leftTurnSignal=False, 
                               rightTurnSignal=False, brakeSignal=False, reverseSignal=False)
    
    def get_front_view(self):
        return self.vehicle.get_image(self.vehicle.CAMERA_CSI_FRONT)
    
    def get_lidar(self, samplePoints, lidar_rate, duration):
        x_data, y_data = [], []

        for count in range(duration):
            success, angle, distance = self.vehicle.get_lidar(samplePoints=samplePoints)
            x = np.sin(angle) * distance
            y = np.cos(angle) * distance
            x_data.append(x)
            y_data.append(y)

            if len(x_data) > 100:  # Limit the number of displayed points
                x_data.pop(0)
                y_data.pop(0)

            self.update_plot(x_data, y_data)
            time.sleep(lidar_rate)

    def update_plot(self, x_data, y_data):
        self.lidarData.set_xdata(x_data)
        self.lidarData.set_ydata(y_data)
        self.fig.canvas.draw()
        self.fig.canvas.flush_events()
        

def main():
    runs = 0
    while True:
        print("\nRun ", runs)
        QCarSim = QCarSimulation()
        QCar = QCarVehicle(actor_number = 1)    # QCar2 = QCarVehicle(actor_number = 2)
        QCar.spawn_vehicle(location=[-8.700, 14.643, 0.005], rotation=[0,0,math.pi/2])
        QCar.set_speed(10, 1)
        time.sleep(1)
        QCar.set_speed(-7, 1)
        time.sleep(1)
        
        # QCar.get_lidar(1000, 0.001, 40)
        # x, camera_image = QCar.get_front_view()
        
        QCarSim.despawn_all()
        time.sleep(1)
        print("Destroy all spawned actors exit code: ", QCarSim.despawn_all())
        exitattempt = 0
        time.sleep(1)
        while QCarSim.despawn_all()<0 and exitattempt <= 100:
            QCarSim.despawn_all()
            exitattempt += 1
        time.sleep(1)
        if QCarSim.despawn_all() <0:
            print("Critical error: could not despawn entities")
            break
        time.sleep(1)
        QCarSim.close_connection()
        
        runs += 1
        if runs % 20 == 0:
            break

        `

**Comment by habibi1195** [comment]
Hi,

Is there anything to report on this issue? I'm still having the same issue. Here is a small test that tests one QCar to spawn and move a little before despawning, in a loop. Without failure, on the 4th loop, qlabs.destroy_all_spawned_actors() returns -1. (Apologies that Github code embed is sturggling to format everything properly)

`from qvl.qlabs import QuanserInteractiveLabs
from qvl.free_camera import QLabsFreeCamera
from qvl.basic_shape import QLabsBasicShape
from qvl.qcar import QLabsQCar
from qvl.environment_outdoors import QLabsEnvironmentOutdoors
import time
import math
import numpy as np
import matplotlib.pyplot as plt
import threading


class QCarSimulation(object):
    """
    Control the simulation of Quanser QCars in the digital twin
    """
    def __init__(self,
                 host='localhost',
                 init_params = None,
                 qlabs = QuanserInteractiveLabs()
                 ):
        self.init_params = init_params
        self.qlabs = qlabs
        self.vehicle = QLabsQCar(self.qlabs)
        self.lock = threading.Lock()
        
        print("Connecting to QLabs...")
        try:
            self.client = qlabs.open(host)
        except:
            print("Unable to connect to QLabs")
            return
        
        print("Connected")
        
    # def spawn_vehicle(self, actorNumber, location, rotation):
    #     self.vehicle.spawn_id(actorNumber=actorNumber, location=location, rotation=rotation)
        
    def despawn_all(self):
        return self.qlabs.destroy_all_spawned_actors()
        
    def spawn_camera(self,actorNumber, location, rotation):
        hCameraQCars = QLabsFreeCamera(self.qlabs)
        hCameraQCars.spawn_id(actorNumber=actorNumber, location=location, rotation=rotation)
        hCameraQCars.possess()
        
    
    def accelerate_forward(self, speed=0, turn=0, headlights=True, leftTurnSignal=False, 
                           rightTurnSignal=False, brakeSignal=False, reverseSignal=False):
        self.vehicle.set_velocity_and_request_state(forward=speed, turn=turn, headlights=True, leftTurnSignal=False, 
                               rightTurnSignal=False, brakeSignal=False, reverseSignal=False)
    
    def forward_times(self, speed=0, turn=0, headlights=True, leftTurnSignal=False, 
                           rightTurnSignal=False, brakeSignal=False, reverseSignal=False):
        x, location, rotation, frontHit, rearHit = self.vehicle.set_velocity_and_request_state(forward=speed, turn=turn, headlights=True, leftTurnSignal=False, 
                               rightTurnSignal=False, brakeSignal=False, reverseSignal=False)
        return x, location, rotation, frontHit, rearHit
    
    def close_connection(self):
        return self.qlabs.close()
    
class QCarVehicle(QCarSimulation):
    def __init__(self, actor_number):
        super().__init__()
        self.actor_number = actor_number
        self.squareSize = 100
        plt.ion()  # Turn on interactive mode for Matplotlib
        self.fig, self.ax = plt.subplots(figsize=(8, 8), dpi=100)
        self.ax.set_xlim(-self.squareSize, self.squareSize)
        self.ax.set_ylim(-self.squareSize, self.squareSize)
        self.ax.set_facecolor('black')  # Set background color to black
        self.lidarData, = self.ax.plot([], [], 'ro', markersize=1)
        
        
    def spawn_vehicle(self, location, rotation):
        return self.vehicle.spawn_id(self.actor_number, location, rotation)
    

    def set_speed(self, speed, duration):
        self.vehicle.set_velocity_and_request_state_degrees(forward=speed, turn = 0, headlights=True, leftTurnSignal=False, 
                               rightTurnSignal=False, brakeSignal=False, reverseSignal=False)
        
        time.sleep(duration)
        
        self.vehicle.set_velocity_and_request_state_degrees(forward=0, turn = 0, headlights=True, leftTurnSignal=False, 
                               rightTurnSignal=False, brakeSignal=False, reverseSignal=False)

    
    def set_turn(self, speed, turn, duration):
        self.vehicle.set_velocity_and_request_state_degrees(forward=speed, turn=turn, headlights=True, leftTurnSignal=False, 
                               rightTurnSignal=False, brakeSignal=False, reverseSignal=False)
        time.sleep(duration)
        self.vehicle.set_velocity_and_request_state_degrees(forward=0, turn=turn, headlights=True, leftTurnSignal=False, 
                               rightTurnSignal=False, brakeSignal=False, reverseSignal=False)
    
    def get_front_view(self):
        return self.vehicle.get_image(self.vehicle.CAMERA_CSI_FRONT)
    
    def get_lidar(self, samplePoints, lidar_rate, duration):
        x_data, y_data = [], []

        for count in range(duration):
            success, angle, distance = self.vehicle.get_lidar(samplePoints=samplePoints)
            x = np.sin(angle) * distance
            y = np.cos(angle) * distance
            x_data.append(x)
            y_data.append(y)

            if len(x_data) > 100:  # Limit the number of displayed points
                x_data.pop(0)
                y_data.pop(0)

            self.update_plot(x_data, y_data)
            time.sleep(lidar_rate)

    def update_plot(self, x_data, y_data):
        self.lidarData.set_xdata(x_data)
        self.lidarData.set_ydata(y_data)
        self.fig.canvas.draw()
        self.fig.canvas.flush_events()
        

def main():
    runs = 0
    while True:
        print("\nRun ", runs)
        QCarSim = QCarSimulation()
        QCar = QCarVehicle(actor_number = 1)    # QCar2 = QCarVehicle(actor_number = 2)
        QCar.spawn_vehicle(location=[-8.700, 14.643, 0.005], rotation=[0,0,math.pi/2])
        QCar.set_speed(10, 1)
        time.sleep(1)
        QCar.set_speed(-7, 1)
        time.sleep(1)
        
        # QCar.get_lidar(1000, 0.001, 40)
        # x, camera_image = QCar.get_front_view()
        
        QCarSim.despawn_all()
        time.sleep(1)
        print("Destroy all spawned actors exit code: ", QCarSim.despawn_all())
        exitattempt = 0
        time.sleep(1)
        while QCarSim.despawn_all()<0 and exitattempt <= 100:
            QCarSim.despawn_all()
            exitattempt += 1
        time.sleep(1)
        if QCarSim.despawn_all() <0:
            print("Critical error: could not despawn entities")
            break
        time.sleep(1)
        QCarSim.close_connection()
        
        runs += 1
        if runs % 20 == 0:
            break

        `

**Comment by mrDataMeetsQ** [comment]
Thanks for the code. The issue is related to an incorrect usage of class objects. We have attached a version with corrected lines, please review them. 

Line 119 instantiates a **QCarSimulation**() class object, and line 120 instantiates a **QCarVehicle**() class object. However, in your **QCarVehicle** is a child class for **QCarSimulation**, and the __init__ function for **QCarVehicle** also instantiates it's parent. As such, you cannot use the **QCarSimulation** instance to destroy objects that were spawned with the **QCarVehicle**'s parent **QCarSimulation** instance. 

Secondly, on line 130, the code was despawning all objects using the **despawn_all** method call. As a result, the following while loop can no longer destroy objects as there are no objects left to despawn. As a result, it returns -1. 

Thank you again for the comment, please let us know if this addresses your concerns.

[tsr_habibi1195.txt](https://github.com/quanser/Quanser_Interactive_Labs_Resources/files/13253718/tsr_habibi1195.txt)
